spring:
  mail:
    host: smtp.163.com
    username: javajwtli111@163.com
    password: NYpVajuWhn7eZYZm
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: asgjkl
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: "061219"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 5371