spring:
  security:
    jwt:
      key: asgjkl
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoyu
    username: root
    password: "061219"
    driver-class-name: com.mysql.cj.jdbc.Driver