spring:
  security:
    filter:
      order: -100
    jwt:
      key: asgjkl
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: "061219"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 5371